### ISSUE TITLE
Article count is messed up on TT-RSS v20.02

### ISSUE THREAD

**Issue by fbearoff** [jonathanherrmannengel/tt-rss_reeder_theme#2]
After updating to TT-RSS v20.02-5f30061c9 the article count box on the left pane is present three times per category, see picture below. 

![article_count](https://user-images.githubusercontent.com/11050285/74959230-32e2ff00-53d8-11ea-862b-c50fa5d3eb1e.png)

**Comment by jonathanherrmannengel** [comment]
Thanks!

Today's commit should fix this bug.
